# Generated by Django 4.2.30 on 2026-08-27 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Код')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='Права')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системная роль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.roleprofile', verbose_name='Настраиваемая роль'),
        ),
    ]
