# Generated by Django 4.2.30 on 2026-06-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_import_schedule_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('shooting', 'Съемка'), ('editing', 'Монтаж'), ('approval', 'На согласовании'), ('review', 'На проверке'), ('done', 'Выполнена'), ('canceled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
