# Generated by Django 4.2.30 on 2026-06-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_mode', models.BooleanField(default=True, verbose_name='Тестовый режим')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Логин терминала')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Пароль терминала')),
                ('token', models.CharField(blank=True, max_length=255, verbose_name='Токен')),
                ('base_url', models.URLField(default='https://pay.alfabank.ru/rest/', verbose_name='Базовый URL АПИ')),
            ],
            options={
                'verbose_name': 'Настройка оплаты',
                'verbose_name_plural': 'Настройки оплаты',
            },
        ),
    ]
