# Generated by hand for YooKassa migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ссылка отправлена'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(
                choices=[('partial', 'Частичная оплата 50%'), ('full', 'Полная оплата')],
                default='full',
                max_length=20,
                verbose_name='Тип оплаты',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(
                choices=[('yookassa', 'YooKassa')],
                default='yookassa',
                max_length=32,
                verbose_name='Провайдер',
            ),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='base_url',
            field=models.URLField(default='https://api.yookassa.ru/v3/', verbose_name='Базовый URL API'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Secret key YooKassa'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Дополнительный токен'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Shop ID YooKassa'),
        ),
    ]
