# Generated by Django 4.2.30 on 2026-06-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Токен доступа клиента',
                'verbose_name_plural': 'Токены доступа клиентов',
                'ordering': ['-created_at'],
            },
        ),
    ]
