# Generated by Django 4.2.30 on 2026-08-27 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0005_client_archived_at'),
        ('projects', '0004_project_archived_at'),
        ('production', '0003_productionsubtask'),
        ('client_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название материала')),
                ('description', models.TextField(blank=True, verbose_name='Комментарий для клиента')),
                ('file', models.FileField(blank=True, upload_to='client_approvals/', verbose_name='Файл')),
                ('external_url', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Желаемый срок ответа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает решения'), ('approved', 'Согласовано'), ('changes_requested', 'Нужны правки')], default='pending', max_length=24, verbose_name='Статус')),
                ('client_comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_approvals', to='clients.client', verbose_name='Клиент')),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_approvals', to='production.production', verbose_name='Продакшен')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_approvals', to='projects.project', verbose_name='Проект')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_material_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Отправил')),
            ],
            options={
                'verbose_name': 'Согласование материала',
                'verbose_name_plural': 'Согласования материалов',
                'ordering': ['-created_at'],
            },
        ),
    ]
